services:
    client:
        container_name: prakticum-client
        image: prakticum-client
        build:
            context: .
            dockerfile: Dockerfile.client
            args:
              CLIENT_PORT: ${CLIENT_PORT}
        restart: always
        expose:
            - "3000"
        ports:
           - "${CLIENT_PORT}:3000"
        environment:
          - CLIENT_PORT=${CLIENT_PORT}
          - SERVER_PORT=${SERVER_PORT}
        depends_on:
          - server
        env_file:
          - .env
    server:
        container_name: prakticum-server
        image: prackicum-server
        build:
            context: .
            dockerfile: Dockerfile.server
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        expose: 
            - "3001"
        environment:
          SERVER_PORT: ${SERVER_PORT}
          POSTGRES_HOST: ${POSTGRES_HOST}
          EXTERNAL_SERVER_URL: ${EXTERNAL_SERVER_URL}
        depends_on:
          - postgres
        env_file:
          - .env

    postgres:
      container_name: prakticum-pg
      image: postgres:14  
      expose: 
          - "5432"  
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      env_file:
      - .env

    nginx:
      container_name: prakticum-nginx
      image: nginx:latest
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./nginx/privkey.pem:/etc/nginx/privkey.pem
          - ./nginx/fullchain.pem:/etc/nginx/fullchain.pem
      depends_on:
          - client
          - server
