export { default as LoginPage } from './login/LoginPage'
export { default as RegistrationPage } from './registration/RegistrationPage'
export { default as ForumPage } from './forum/ForumPage'
export { default as ForumTopicPage } from './forum/ForumTopicPage'
export { default as GamePage } from './game/GamePage'
export { default as HomePage } from './home/HomePage'
export { default as LeaderboardPage } from './leaderboard/LeaderboardPage'
export { default as NotFoundPage } from './not-found/NotFoundPage'
export { default as ProfilePage } from './profile/ProfilePage'
export { ServerErrorPage } from './server-error-page/ServerErrorPage'
